Repository NBC-Final-Team6/ToTheMoon, pull requests merged in 2025-02, with the labels that each got.

#38 [#30]: CoinPriceView 이미지 추가 및 디자인
  ToTheMoon/ToTheMoon/Assets.xcassets/MarketImage/Bithumb.imageset/Contents.json
  ToTheMoon/ToTheMoon/Assets.xcassets/MarketImage/Bithumb.imageset/bithumb_symbol_RGB_full color.png
  ToTheMoon/ToTheMoon/Assets.xcassets/MarketImage/Coinone.imageset/Contents.json
  ToTheMoon/ToTheMoon/Assets.xcassets/MarketImage/Coinone.imageset/pngwing.com (1).png
  ToTheMoon/ToTheMoon/Assets.xcassets/MarketImage/Contents.json
  ToTheMoon/ToTheMoon/Assets.xcassets/MarketImage/Korbit.imageset/Contents.json
  ToTheMoon/ToTheMoon/Assets.xcassets/MarketImage/Korbit.imageset/korbit-seeklogo.png
  ToTheMoon/ToTheMoon/Assets.xcassets/MarketImage/Upbit.imageset/Contents.json
  ToTheMoon/ToTheMoon/Assets.xcassets/MarketImage/Upbit.imageset/pngwing.com (2).png
  ToTheMoon/ToTheMoon/Assets.xcassets/코인원.imageset/Contents.json
  ToTheMoon/ToTheMoon/Model/CoinPriceModel.swift
  ToTheMoon/ToTheMoon/View/CoinPrice/CoinPriceTableViewCell.swift
  ToTheMoon/ToTheMoon/View/CoinPrice/CoinPriceView.swift
  ToTheMoon/ToTheMoon/View/CoinPrice/CoinPriceViewController.swift
  ToTheMoon/ToTheMoon/View/CoinPrice/MarketView.swift
  ToTheMoon/ToTheMoon/ViewModel/CoinPriceViewModel.swift
Labels: feature

#36 [#15] : SettingView화면 구현
  ToTheMoon/ToTheMoon/View/Setting/InformationView.swift
  ToTheMoon/ToTheMoon/View/Setting/InformationViewController.swift
  ToTheMoon/ToTheMoon/View/Setting/NotificationSettingView.swift
  ToTheMoon/ToTheMoon/View/Setting/NotificationSettingViewController.swift
  ToTheMoon/ToTheMoon/View/Setting/ScreenModeView.swift
  ToTheMoon/ToTheMoon/View/Setting/ScreenModeViewController.swift
  ToTheMoon/ToTheMoon/View/Setting/SettingView.swift
  ToTheMoon/ToTheMoon/View/Setting/SettingViewController.swift
Labels: feature

#40 [#33]: SearchView 코어데이터에 추가하기 기능 구현, 검색 로직 수정 작업 및 관심 목록 뷰 구현 완료
  ToTheMoon.zip
  ToTheMoon/ToTheMoon.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ToTheMoon/ToTheMoon/Common/CoreDataManager.swift
  ToTheMoon/ToTheMoon/Model/Shared/MarketPrice.swift
  ToTheMoon/ToTheMoon/Repository/CoinImageCache.swift
  ToTheMoon/ToTheMoon/SceneDelegate.swift
  ToTheMoon/ToTheMoon/Services/CoinOneService.swift
  ToTheMoon/ToTheMoon/Services/SymbolService.swift
  ToTheMoon/ToTheMoon/UseCase/ManageFavoritesUseCase.swift
  ToTheMoon/ToTheMoon/View/CoinPrice/CoinPriceTableViewCell.swift
  ToTheMoon/ToTheMoon/View/Favorites/FavoriteListViewController.swift
  ToTheMoon/ToTheMoon/View/Favorites/FavoritesContainerViewController.swift
  ToTheMoon/ToTheMoon/View/Favorites/FavoritesView.swift
  ToTheMoon/ToTheMoon/View/Favorites/FavoritesViewController.swift
  ToTheMoon/ToTheMoon/View/Favorites/FovoritesListTableView.swift
  ToTheMoon/ToTheMoon/View/Favorites/LoadingView.swift
  ToTheMoon/ToTheMoon/View/Favorites/NoFavoritesView.swift
  ToTheMoon/ToTheMoon/View/Favorites/PopularCurrencyTableView.swift
  ToTheMoon/ToTheMoon/View/Favorites/PopularCurrencyViewController.swift
  ToTheMoon/ToTheMoon/View/Favorites/TopFavoritesView.swift
  ToTheMoon/ToTheMoon/View/Search/FavoritesViewCell.swift
  ToTheMoon/ToTheMoon/View/Search/SearchView.swift
  ToTheMoon/ToTheMoon/View/Search/SearchViewController.swift
  ToTheMoon/ToTheMoon/View/TabBar/CustomTabBarViewController.swift
  ToTheMoon/ToTheMoon/ViewModel/FavoritesContainerViewModel.swift
  ToTheMoon/ToTheMoon/ViewModel/FavoritesListViewModel.swift
  ToTheMoon/ToTheMoon/ViewModel/FavoritesViewModel.swift
  ToTheMoon/ToTheMoon/ViewModel/PopularCurrencyViewModel.swift
  ToTheMoon/ToTheMoon/ViewModel/SearchViewModel.swift
Labels: feature

#42 [#15] : SettingView 디자인 수정 및 다크모드 라이트모드 적용
  ToTheMoon/ToTheMoon/SceneDelegate.swift
  ToTheMoon/ToTheMoon/View/Setting/InformationView.swift
  ToTheMoon/ToTheMoon/View/Setting/InformationViewController.swift
  ToTheMoon/ToTheMoon/View/Setting/NotificationSettingView.swift
  ToTheMoon/ToTheMoon/View/Setting/NotificationSettingViewController.swift
  ToTheMoon/ToTheMoon/View/Setting/ScreenModeView.swift
  ToTheMoon/ToTheMoon/View/Setting/ScreenModeViewController.swift
  ToTheMoon/ToTheMoon/View/Setting/SettingView.swift
  ToTheMoon/ToTheMoon/View/Setting/SettingViewController.swift
Labels: fix

#44 [#27] : 코인 정보 UI 개선 및 스크롤뷰, 코인 심볼 및 거래소 정보, 차트데이터 기능 구현
  ToTheMoon/ToTheMoon.xcodeproj/project.pbxproj
  ToTheMoon/ToTheMoon.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ToTheMoon/ToTheMoon/Assets.xcassets/coin_images/vulcan-forged.imageset/Contents.json
  ToTheMoon/ToTheMoon/Common/Network/NetworkError.swift
  ToTheMoon/ToTheMoon/Services/SymbolService.swift
  ToTheMoon/ToTheMoon/View/Chart/ChartView.swift
  ToTheMoon/ToTheMoon/View/Chart/ChartViewController.swift
  ToTheMoon/ToTheMoon/View/CoinPrice/CoinPriceViewController.swift
  ToTheMoon/ToTheMoon/View/TabBar/CustomTabBarViewController.swift
  ToTheMoon/ToTheMoon/ViewModel/ChartViewModel.swift
  ToTheMoon/ToTheMoon/ViewModel/CoinPriceViewModel.swift
Labels: feature

#47 [#41]: CoinPriceView 미니 차트 구현
  ToTheMoon/ToTheMoon/View/CoinPrice/CoinPriceTableViewCell.swift
  ToTheMoon/ToTheMoon/View/CoinPrice/CoinPriceViewController.swift
  ToTheMoon/ToTheMoon/View/CoinPrice/SimpleChartView.swift
  ToTheMoon/ToTheMoon/ViewModel/CoinPriceViewModel.swift
Labels: feature

#51 [#50]: coinpriceview chart
  ToTheMoon/ToTheMoon/View/CoinPrice/CoinPriceTableViewCell.swift
  ToTheMoon/ToTheMoon/View/CoinPrice/CoinPriceView.swift
  ToTheMoon/ToTheMoon/View/CoinPrice/CoinPriceViewController.swift
  ToTheMoon/ToTheMoon/View/CoinPrice/MarketView.swift
  ToTheMoon/ToTheMoon/View/TabBar/CustomTabBarViewController.swift
  ToTheMoon/ToTheMoon/ViewModel/CoinPriceViewModel.swift
Labels: feature, fix

#52 [#48] chartviewrefactoring
  ToTheMoon/ToTheMoon/View/Chart/ChartView.swift
  ToTheMoon/ToTheMoon/View/Chart/ChartViewController.swift
  ToTheMoon/ToTheMoon/View/CoinPrice/CoinPriceTableViewCell.swift
  ToTheMoon/ToTheMoon/ViewModel/ChartViewModel.swift
Labels: refactor

#66 [Fix]: 마켓 레이블 기기에 맞춰 높이 수정
  ToTheMoon/ToTheMoon/View/CoinPrice/CoinPriceView.swift
  ToTheMoon/ToTheMoon/View/CoinPrice/CoinPriceViewController.swift
Labels: fix

#69 [#4]: 탭바 위치 조정 및 Assets NumbersColor 라이트 모드 색상 변경
  ToTheMoon/ToTheMoon/Assets.xcassets/Color/NumbersGreenColor.colorset/Contents.json
  ToTheMoon/ToTheMoon/View/TabBar/CustomTabBarViewController.swift
Labels: fix

#74 [#41]: coinpriceview chart 불러오는 시간 범위 변경
  ToTheMoon/ToTheMoon/View/CoinPrice/SimpleChartView.swift
  ToTheMoon/ToTheMoon/ViewModel/CoinPriceViewModel.swift
Labels: fix

#75 [#72]: websocket 구현
  ToTheMoon/ToTheMoon.xcodeproj/project.pbxproj
  ToTheMoon/ToTheMoon.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ToTheMoon/ToTheMoon/AppDelegate.swift
  ToTheMoon/ToTheMoon/Common/Network/Exchange.swift
  ToTheMoon/ToTheMoon/Common/Network/RESTFul/NetworkError.swift
  ToTheMoon/ToTheMoon/Common/Network/RESTFul/NetworkManager.swift
  ToTheMoon/ToTheMoon/Common/Network/WebSokcet/BaseWebSocketManager.swift
  ToTheMoon/ToTheMoon/Common/Network/WebSokcet/BithumbWebSocketManager.swift
  ToTheMoon/ToTheMoon/Common/Network/WebSokcet/CoinoneWebSocketManager.swift
  ToTheMoon/ToTheMoon/Common/Network/WebSokcet/KorbitWebSocketManager.swift
  ToTheMoon/ToTheMoon/Common/Network/WebSokcet/UpbitWebSocketManager.swift
  ToTheMoon/ToTheMoon/Common/Network/WebSokcet/WebSocketError.swift
  ToTheMoon/ToTheMoon/Model/Bithumb/RESTFul/BithumbCandleResponse.swift
  ToTheMoon/ToTheMoon/Model/Bithumb/RESTFul/BithumbMarketResponse.swift
  ToTheMoon/ToTheMoon/Model/Bithumb/RESTFul/BithumbTickerResponse.swift
  ToTheMoon/ToTheMoon/Model/Bithumb/RESTFul/BithumbTickersResponse.swift
  ToTheMoon/ToTheMoon/Model/Bithumb/WebSocket/BithumbWebSocketResponse.swift
  ToTheMoon/ToTheMoon/Model/Bithumb/WebSocket/BithumbWebSocketTickerRequest.swift
  ToTheMoon/ToTheMoon/Model/Bithumb/WebSocket/Untitled.swift
  ToTheMoon/ToTheMoon/Model/CoinOne/RESTFul/CoinOneCandleResponse.swift
  ToTheMoon/ToTheMoon/Model/CoinOne/RESTFul/CoinOneTickerResponse.swift
  ToTheMoon/ToTheMoon/Model/CoinOne/WebSocket/CoinoneWebSocketRequest.swift
  ToTheMoon/ToTheMoon/Model/CoinOne/WebSocket/CoinoneWebSocketResponse.swift
  ToTheMoon/ToTheMoon/Model/Korbit/RESTFul/KorbitCandleResponse.swift
  ToTheMoon/ToTheMoon/Model/Korbit/RESTFul/KorbitMarketResponse.swift
  ToTheMoon/ToTheMoon/Model/Korbit/RESTFul/KorbitTickerResponse.swift
  ToTheMoon/ToTheMoon/Model/Korbit/WebSocket/KorbitWebSocketRequest.swift
  ToTheMoon/ToTheMoon/Model/Korbit/WebSocket/KorbitWebSocketResponse.swift
  ToTheMoon/ToTheMoon/Model/Upbit/RESTFul/UpbitCandleResponse.swift
  ToTheMoon/ToTheMoon/Model/Upbit/RESTFul/UpbitTickerResponse.swift
  ToTheMoon/ToTheMoon/Model/Upbit/WebSocket/AnyEncodable.swift
  ToTheMoon/ToTheMoon/Model/Upbit/WebSocket/UpbitWebSocketTickerResponse.swift
  ToTheMoon/ToTheMoon/Services/BithumbService.swift
  ToTheMoon/ToTheMoon/Services/Btihumb/BithumbService.swift
  ToTheMoon/ToTheMoon/Services/Btihumb/BithumbWebSocketService.swift
  ToTheMoon/ToTheMoon/Services/CoinOne/CoinOneService.swift
  ToTheMoon/ToTheMoon/Services/CoinOne/CoinoneWebSocketService.swift
  ToTheMoon/ToTheMoon/Services/CoinOneService.swift
  ToTheMoon/ToTheMoon/Services/Common/BaseService.swift
  ToTheMoon/ToTheMoon/Services/Common/SymbolService.swift
  ToTheMoon/ToTheMoon/Services/Korbit/KorbitService.swift
  ToTheMoon/ToTheMoon/Services/Korbit/KorbitWebSocketService.swift
  ToTheMoon/ToTheMoon/Services/KorbitService.swift
  ToTheMoon/ToTheMoon/Services/Upbit/UpbitService.swift
  ToTheMoon/ToTheMoon/Services/Upbit/UpbitWebSocketService.swift
  ToTheMoon/ToTheMoon/Services/UpbitService.swift
Labels: feature

#78 [Refactoring]: networkrefactoring
  ToTheMoon/ToTheMoon/Model/Bithumb/WebSocket/Untitled.swift
  ToTheMoon/ToTheMoon/Services/Btihumb/BithumbService.swift
  ToTheMoon/ToTheMoon/Services/CoinOne/CoinOneService.swift
  ToTheMoon/ToTheMoon/Services/Common/ServiceProtocol.swift
  ToTheMoon/ToTheMoon/Services/Korbit/KorbitService.swift
  ToTheMoon/ToTheMoon/Services/Upbit/UpbitService.swift
  ToTheMoon/ToTheMoon/UseCase/GetMarketPricesUseCase.swift
  ToTheMoon/ToTheMoon/View/Favorites/FavoriteListViewController.swift
  ToTheMoon/ToTheMoon/View/Favorites/FavoritesContainerViewController.swift
  ToTheMoon/ToTheMoon/ViewModel/PopularCurrencyViewModel.swift
Labels: refactor

#81 [#80]: CustomTabBar refactoring
  ToTheMoon/ToTheMoon/View/TabBar/CustomTabBarView.swift
  ToTheMoon/ToTheMoon/View/TabBar/CustomTabBarViewController.swift
Labels: refactor

#79 [#73]: coinpriceview refactoring
  ToTheMoon/ToTheMoon/View/CoinPrice/CoinPriceViewController.swift
  ToTheMoon/ToTheMoon/ViewModel/CoinPriceViewModel.swift
Labels: refactor

#84 [Refactoring]: favoritesViewRefactoring
  ToTheMoon/ToTheMoon.xcodeproj/project.pbxproj
  ToTheMoon/ToTheMoon/AppDelegate.swift
  ToTheMoon/ToTheMoon/Common/Network/WebSokcet/BaseWebSocketManager.swift
  ToTheMoon/ToTheMoon/Common/Network/WebSokcet/BithumbWebSocketManager.swift
  ToTheMoon/ToTheMoon/Common/Network/WebSokcet/CoinoneWebSocketManager.swift
  ToTheMoon/ToTheMoon/Common/Network/WebSokcet/KorbitWebSocketManager.swift
  ToTheMoon/ToTheMoon/Common/Network/WebSokcet/UpbitWebSocketManager.swift
  ToTheMoon/ToTheMoon/Common/Network/WebSokcet/WebSocketError.swift
  ToTheMoon/ToTheMoon/Extension/UIViewController+Rx.swift
  ToTheMoon/ToTheMoon/Services/Btihumb/BithumbWebSocketService.swift
  ToTheMoon/ToTheMoon/Services/CoinOne/CoinoneWebSocketService.swift
  ToTheMoon/ToTheMoon/Services/Korbit/KorbitWebSocketService.swift
  ToTheMoon/ToTheMoon/Services/Upbit/UpbitWebSocketService.swift
  ToTheMoon/ToTheMoon/UseCase/ManageFavoritesUseCase.swift
  ToTheMoon/ToTheMoon/View/CoinPrice/CoinPriceTableViewCell.swift
  ToTheMoon/ToTheMoon/View/Favorites/FavoriteListViewController.swift
  ToTheMoon/ToTheMoon/View/Search/SearchViewController.swift
  ToTheMoon/ToTheMoon/ViewModel/FavoritesListViewModel.swift
  ToTheMoon/ToTheMoonTests/ToTheMoonTests.swift
Labels: refactor

#86 [#73]: coinpriceview에 검색기능 추가
  ToTheMoon/ToTheMoon/View/CoinPrice/CoinPriceView.swift
  ToTheMoon/ToTheMoon/View/CoinPrice/CoinPriceViewController.swift
  ToTheMoon/ToTheMoon/ViewModel/FavoritesListViewModel.swift
Labels: feature

#87 [Refactoring]: favoritesviewrefactoring
  ToTheMoon/ToTheMoon/AppDelegate.swift
  ToTheMoon/ToTheMoon/Common/Coin+CoreDataClass.swift
  ToTheMoon/ToTheMoon/Common/Coin+CoreDataProperties.swift
  ToTheMoon/ToTheMoon/Common/CoinEntities+CoreDataClass.swift
  ToTheMoon/ToTheMoon/Common/CoinEntities+CoreDataProperties.swift
  ToTheMoon/ToTheMoon/Common/CoreDataManager.swift
  ToTheMoon/ToTheMoon/Common/Network/Exchange.swift
  ToTheMoon/ToTheMoon/Common/Network/WebSokcet/BaseWebSocketManager.swift
  ToTheMoon/ToTheMoon/Common/Network/WebSokcet/BithumbWebSocketManager.swift
  ToTheMoon/ToTheMoon/Common/Network/WebSokcet/CoinoneWebSocketManager.swift
  ToTheMoon/ToTheMoon/Common/Network/WebSokcet/KorbitWebSocketManager.swift
  ToTheMoon/ToTheMoon/Common/Network/WebSokcet/UpbitWebSocketManager.swift
  ToTheMoon/ToTheMoon/Common/ToTheMoon.xcdatamodeld/ToTheMoon.xcdatamodel/contents
  ToTheMoon/ToTheMoon/Extension/UIViewController+Rx.swift
  ToTheMoon/ToTheMoon/Model/Shared/CandleInterval.swift
  ToTheMoon/ToTheMoon/Services/Btihumb/BithumbWebSocketService.swift
  ToTheMoon/ToTheMoon/Services/CoinOne/CoinoneWebSocketService.swift
  ToTheMoon/ToTheMoon/Services/Common/WebSocketServiceProtocol.swift
  ToTheMoon/ToTheMoon/Services/Korbit/KorbitWebSocketService.swift
  ToTheMoon/ToTheMoon/Services/Upbit/UpbitWebSocketService.swift
  ToTheMoon/ToTheMoon/UseCase/ChartUseCase.swift
  ToTheMoon/ToTheMoon/UseCase/FetchFavoriteCoinsChartUseCase.swift
  ToTheMoon/ToTheMoon/UseCase/FetchFavoriteCoinsUseCase.swift
  ToTheMoon/ToTheMoon/UseCase/ManageFavoritesUseCase.swift
  ToTheMoon/ToTheMoon/View/Chart/ChartViewController.swift
  ToTheMoon/ToTheMoon/View/Favorites/FavoriteListViewController.swift
  ToTheMoon/ToTheMoon/View/Favorites/FavoritesContainerViewController.swift
  ToTheMoon/ToTheMoon/View/Favorites/NoFavoritesView.swift
  ToTheMoon/ToTheMoon/ViewModel/ChartViewModel.swift
  ToTheMoon/ToTheMoon/ViewModel/FavoritesListViewModel.swift
  ToTheMoon/ToTheMoon/ViewModel/SearchViewModel.swift
Labels: feature

#91 [# 88 Refactoring]: favoritesviewrefactoringv2
  ToTheMoon/ToTheMoon.xcodeproj/project.pbxproj
  ToTheMoon/ToTheMoon.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ToTheMoon/ToTheMoon/Model/Shared/Candle.swift
  ToTheMoon/ToTheMoon/Model/Shared/MarketPrice.swift
  ToTheMoon/ToTheMoon/Model/Shared/MarketPriceWithCandles.swift
  ToTheMoon/ToTheMoon/View/Favorites/FavoriteListViewController.swift
  ToTheMoon/ToTheMoon/View/Favorites/FavoritesContainerViewController.swift
  ToTheMoon/ToTheMoon/View/Favorites/FovoritesListTableViewCell.swift
  ToTheMoon/ToTheMoon/View/Favorites/PopularCurrencyTableView.swift
  ToTheMoon/ToTheMoon/View/Favorites/PopularCurrencyViewController.swift
  ToTheMoon/ToTheMoon/View/Favorites/TabCell.swift
  ToTheMoon/ToTheMoon/View/Favorites/TopFavoritesView.swift
  ToTheMoon/ToTheMoon/View/TabBar/CustomTabBarViewController.swift
  ToTheMoon/ToTheMoon/ViewModel/FavoritesListViewModel.swift
Labels: feature

#92 [#89]: coinpriceview 차트 업데이트
  ToTheMoon/ToTheMoon/Model/CoinPriceModel.swift
  ToTheMoon/ToTheMoon/View/CoinPrice/CoinPriceTableViewCell.swift
  ToTheMoon/ToTheMoon/View/CoinPrice/SimpleChartView.swift
  ToTheMoon/ToTheMoon/ViewModel/CoinPriceViewModel.swift
Labels: feature

#93 [Fix]: SettingViewRefactoring / 중복 파일 삭제
  ToTheMoon/ToTheMoon/View/Setting/ScreenViewModel.swift
Labels: fix

#102 [Update] : 코인 시세 화면이 첫번쨰로 등장하게 수정
  ToTheMoon/ToTheMoon/View/TabBar/CustomTabBarView.swift
  ToTheMoon/ToTheMoon/View/TabBar/CustomTabBarViewController.swift
Labels: Update

#106 [Fix]: 디벨롭 싱크 맞추기
  ToTheMoon/ToTheMoon/View/TabBar/CustomTabBarViewController.swift
Labels: fix

#100 [#98]: searchviewrefactoring
  ToTheMoon/ToTheMoon/Assets.xcassets/coin_images/bithumb.imageset/Contents.json
  ToTheMoon/ToTheMoon/Assets.xcassets/coin_images/bithumb.imageset/bithumb_symbol_RGB_full color.png
  ToTheMoon/ToTheMoon/Assets.xcassets/coin_images/coinone.imageset/Contents.json
  ToTheMoon/ToTheMoon/Assets.xcassets/coin_images/coinone.imageset/pngwing.com (1).png
  ToTheMoon/ToTheMoon/Assets.xcassets/coin_images/korbit.imageset/Contents.json
  ToTheMoon/ToTheMoon/Assets.xcassets/coin_images/korbit.imageset/pngwing.com.png
  ToTheMoon/ToTheMoon/Assets.xcassets/coin_images/upbit.imageset/Contents.json
  ToTheMoon/ToTheMoon/Assets.xcassets/coin_images/upbit.imageset/pngwing.com (2).png
  ToTheMoon/ToTheMoon/Repository/CoinImageCache.swift
  ToTheMoon/ToTheMoon/Repository/ImageRepository.swift
  ToTheMoon/ToTheMoon/View/Favorites/FavoriteListViewController.swift
  ToTheMoon/ToTheMoon/View/Search/SearchView.swift
  ToTheMoon/ToTheMoon/View/Search/SearchViewController.swift
  ToTheMoon/ToTheMoon/ViewModel/FavoritesListViewModel.swift
  ToTheMoon/ToTheMoon/ViewModel/SearchViewModel.swift
Labels: feature, refactor

#104 [#89]: coinpriceview 빗썸 문제 해결
  ToTheMoon.zip
  ToTheMoon/ToTheMoon.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ToTheMoon/ToTheMoon/Assets.xcassets/AccentColor.colorset/Contents.json
  ToTheMoon/ToTheMoon/Assets.xcassets/코인원.imageset/Contents.json
  ToTheMoon/ToTheMoon/View/CoinPrice/CoinPriceViewController.swift
  ToTheMoon/ToTheMoon/ViewModel/CoinPriceViewModel.swift
Labels: fix

#108 화면 연결
  ToTheMoon/ToTheMoon/View/Favorites/FavoriteListViewController.swift
  ToTheMoon/ToTheMoon/View/Search/SearchViewController.swift
Labels: feature

#111 [Fix]: 웹소켓 연결 문제, 즐겨찾기 따로 노는 문제 해결
  ToTheMoon/ToTheMoon/UseCase/ManageFavoritesUseCase.swift
  ToTheMoon/ToTheMoon/View/Chart/ChartViewController.swift
  ToTheMoon/ToTheMoon/ViewModel/ChartViewModel.swift
Labels: bug

#112 1.1 버전에 수정 사항 적용
  ToTheMoon/ToTheMoon/UseCase/ManageFavoritesUseCase.swift
  ToTheMoon/ToTheMoon/View/Chart/ChartViewController.swift
  ToTheMoon/ToTheMoon/ViewModel/ChartViewModel.swift
Labels: fix

#116 [Fix]: 이미지 오류 문제 해결
  ToTheMoon/ToTheMoon/Assets.xcassets/LaunchImage.imageset/Contents.json
  ToTheMoon/ToTheMoon/Assets.xcassets/LaunchImage.imageset/제목을-입력해주세요_-002 (3) 19.png
  ToTheMoon/ToTheMoon/Assets.xcassets/LaunchImage.imageset/제목을-입력해주세요_-002 (3) 20.png
  ToTheMoon/ToTheMoon/Assets.xcassets/LaunchImage.imageset/제목을-입력해주세요_-002 (3) 21.png
  ToTheMoon/ToTheMoon/Assets.xcassets/LaunchImage.imageset/제목을-입력해주세요_-002 (3) 22.png
  ToTheMoon/ToTheMoon/Assets.xcassets/LaunchImage.imageset/제목을-입력해주세요_-002 (3) 23.png
  ToTheMoon/ToTheMoon/Assets.xcassets/LaunchImage.imageset/제목을-입력해주세요_-002 (3) 24.png
  ToTheMoon/ToTheMoon/Assets.xcassets/LaunchImage.imageset/제목을-입력해주세요_-002 (3) 25.png
  ToTheMoon/ToTheMoon/Assets.xcassets/LaunchImage.imageset/제목을-입력해주세요_-002 (3) 26.png
  ToTheMoon/ToTheMoon/Assets.xcassets/LaunchImage.imageset/제목을-입력해주세요_-002 (3) 27.png
Labels: bug

#119 [#117]: 추가 기능 - 알림 편집 창 UI 구현
  ToTheMoon/ToTheMoon/Assets.xcassets/LaunchImage.imageset/Contents.json
  ToTheMoon/ToTheMoon/Assets.xcassets/LaunchImage.imageset/launch 1.png
  ToTheMoon/ToTheMoon/Assets.xcassets/LaunchImage.imageset/launch 2.png
  ToTheMoon/ToTheMoon/Assets.xcassets/LaunchImage.imageset/launch.png
  ToTheMoon/ToTheMoon/View/Alarm/AlarmEditView.swift
  ToTheMoon/ToTheMoon/View/Alarm/AlarmEditViewController.swift
Labels: feature

#121 [Fix] : 화면 모드 설정 , 앱 설정 화면 separator 색상 기본값으로 변경
  ToTheMoon/ToTheMoon/View/Setting/ScreenModeView.swift
  ToTheMoon/ToTheMoon/View/Setting/SettingView.swift
  ToTheMoon/ToTheMoon/View/TabBar/CustomTabBarViewController.swift
Labels: fix

#122 [#117]: 알림 편집 창 UI 업데이트
  ToTheMoon/ToTheMoon/Assets.xcassets/LaunchImage.imageset/제목을-입력해주세요_-002 (3) 19.png
  ToTheMoon/ToTheMoon/Assets.xcassets/LaunchImage.imageset/제목을-입력해주세요_-002 (3) 20.png
  ToTheMoon/ToTheMoon/Assets.xcassets/LaunchImage.imageset/제목을-입력해주세요_-002 (3) 21.png
  ToTheMoon/ToTheMoon/Assets.xcassets/LaunchImage.imageset/제목을-입력해주세요_-002 (3) 22.png
  ToTheMoon/ToTheMoon/Assets.xcassets/LaunchImage.imageset/제목을-입력해주세요_-002 (3) 23.png
  ToTheMoon/ToTheMoon/Assets.xcassets/LaunchImage.imageset/제목을-입력해주세요_-002 (3) 24.png
  ToTheMoon/ToTheMoon/Assets.xcassets/LaunchImage.imageset/제목을-입력해주세요_-002 (3) 25.png
  ToTheMoon/ToTheMoon/Assets.xcassets/LaunchImage.imageset/제목을-입력해주세요_-002 (3) 26.png
  ToTheMoon/ToTheMoon/Assets.xcassets/LaunchImage.imageset/제목을-입력해주세요_-002 (3) 27.png
  ToTheMoon/ToTheMoon/View/Alarm/AlarmEditView.swift
Labels: Update

#129 Alarmviewmodel1
  ToTheMoon/GoogleService-Info.plist
  ToTheMoon/ToTheMoon.xcodeproj/project.pbxproj
  ToTheMoon/ToTheMoon.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ToTheMoon/ToTheMoon/AppDelegate.swift
  ToTheMoon/ToTheMoon/Common/PriceAlertManager.swift
  ToTheMoon/ToTheMoon/Info.plist
  ToTheMoon/ToTheMoon/Model/Shared/MarketPrice.swift
  ToTheMoon/ToTheMoon/Model/Shared/PriceAlert.swift
  ToTheMoon/ToTheMoon/SceneDelegate.swift
  ToTheMoon/ToTheMoon/ToTheMoon.entitlements
  ToTheMoon/ToTheMoon/View/Alarm/AlarmEditView.swift
  ToTheMoon/ToTheMoon/View/Alarm/AlarmEditViewController.swift
  ToTheMoon/ToTheMoon/View/Chart/ChartView.swift
  ToTheMoon/ToTheMoon/View/Chart/ChartViewController.swift
  ToTheMoon/ToTheMoon/View/TabBar/CustomTabBarViewController.swift
  ToTheMoon/ToTheMoon/ViewModel/AlarmEditViewModel.swift
Labels: feature

#131 [Fix]: 없어진 메서드 추가
  ToTheMoon/ToTheMoon/View/Chart/ChartViewController.swift
Labels: fix

#132 [Update]: 알림 편집 가격 천 단위 콤마, 가격 지정 +/- 버튼 기능 구현
  ToTheMoon/ToTheMoon/View/Alarm/AlarmEditView.swift
  ToTheMoon/ToTheMoon/View/Alarm/AlarmEditViewController.swift
Labels: Update
